app/models/bike.rb, app/models/cart.rb, app/models/category.rb, app/models/order.rb, app/models/review.rb, app/models/user.rb, db/migrate/20230927145402_create_categories.rb, db/migrate/20230927150039_create_bikes.rb, db/migrate/20230927150626_create_orders.rb, db/migrate/20230927150837_create_carts.rb, db/migrate/20230927151037_create_reviews.rb, db/schema.rb, test/models/bike_test.rb, test/models/cart_test.rb, test/models/category_test.rb, test/models/order_test.rb, test/models/review_test.rb
I create these models including validation.
=> Add models

config/routes.rb
=> category-bike-order-routes-setup

app/models/bike.rb, db/seeds.rb
=> category seed and bike seed added

app/assets/stylesheets/components/_bike_grid.scss, app/assets/stylesheets/components/_index.scss, app/controllers/bikes_controller.rb, app/views/bikes/index.html.erb, app/views/layouts/application.html.erb, test/controllers/bikes_controller_test.rb
=> Bike controller view

app/controllers/orders_controller.rb, app/views/bikes/index.html.erb, test/controllers/orders_controller_test.rb
=> generated orders controller and view

Gemfile.lock
This updates the bundler for juans comp
=> Update bundler to solve issue

app/controllers/bikes_controller.rb, app/models/bike.rb, config/environments/development.rb, config/storage.yml, db/migrate/20230929120201_create_active_storage_tables.active_storage.rb, db/schema.rb
=> Seeding bike photos

app/assets/stylesheets/components/_bike_grid.scss, app/views/bikes/index.html.erb, app/views/bikes/show.html.erb, app/views/categories/index.html.erb, db/seeds.rb
- [x ] added cloudinary photos to the index page and show page of bikes
- [x ] added link to the buttons on category index page
- [x ] added link to the buttons on the bike#show page to each bike
Additional notes: pictures are shown, but the page is not rendering all information
=> Cloudinary photos view

app/assets/stylesheets/pages/_Bike-Show.scss, app/assets/stylesheets/pages/_authpage.scss, app/assets/stylesheets/pages/_homepage.scss, app/views/categories/index.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
I just added some style and text to login page and category
=> (some style and text  added to logingpage and category

app/assets/stylesheets/components/_bike_grid.scss, app/assets/stylesheets/pages/_Bike-Show.scss
=> changed the style for bike

app/assets/stylesheets/components/_bike_grid.scss
-[x] added 1fr to the _bike-grid.scss
=> added one grid to the bikes index page

app/controllers/carts_controller.rb, app/controllers/orders_controller.rb, test/controllers/carts_controller_test.rb
crats and orders controller and views are created
there was a problem in orders controller i just deleted and created again
=> crats and orders controller and views are created

app/assets/stylesheets/components/_bike_grid.scss, app/assets/stylesheets/components/_bike_picture.scss, app/assets/stylesheets/components/_index.scss, app/views/bikes/index.html.erb, app/views/bikes/show.html.erb
=> bike index page image styled

app/assets/stylesheets/pages/_Bike-Show.scss, app/views/bikes/show.html.erb
=> Finish with the view of Show

app/assets/stylesheets/pages/_Bike-Show.scss
it is only for checking  there is no code
=> it is only for cheking

app/controllers/bikes_controller.rb, app/controllers/carts_controller.rb, app/controllers/orders_controller.rb, app/models/bike.rb, app/models/user.rb, db/migrate/20231006150310_add_purchasedd_to_bikes.rb, db/schema.rb
basked and some other errors are fixed but still we need to add some text in cart page otherwise the user don't know where he is
=>  bsked and some othre errors are fixed

app/controllers/carts_controller.rb, db/migrate/20231007220343_add_ordered_to_carts.rb, db/schema.rb
carts issue is fixed now carts will disappear when they ordered
=> carts issue is fixed

app/assets/stylesheets/components/_navbar.scss, app/views/carts/index.html.erb, app/views/shared/_navbar.html.erb
=> fixed navbar icon display

app/controllers/application_controller.rb, app/models/user.rb, app/views/bikes/index.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/shared/_navbar.html.erb
avatar pic is working now user can add own pic
=> Avatar is done

app/views/devise/registrations/edit.html.erb
-[x] changed the profile picture in edit page
=> changed default profile page in edit view

.vscode/settings.json, Gemfile.lock, app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_colors.scss, app/controllers/application_controller.rb, app/controllers/orders_controller.rb, app/javascript/controllers/hello_controller.js, app/views/layouts/application.html.erb, app/views/orders/index.html.erb, db/schema.rb
Added animation to alert for @Shakar-coder 😄 He is the best 🙄
=> Added animation for notice
